CREATE DATABASE MARKET
CREATE TABLE PRODUCTS (ID INT , [NAME] NVARCHAR , PRICE INT);
ALTER TABLE PRODUCTS ADD [BRAND] NVARCHAR;
ALTER TABLE master.dbo.PRODUCTS
ALTER COLUMN [NAME] NVARCHAR(100) NULL;
ALTER TABLE master.dbo.PRODUCTS
ALTER COLUMN [BRAND] NVARCHAR(100) NULL;
INSERT INTO PRODUCTS (ID, [NAME], PRICE,[BRAND])
VALUES
(1,'MEYVE',20,'MEYVELI'),
(2,'KITAB', 15, 'KITABCI'),
(3, 'MASIN',10000,'MASINCI');

UPDATE PRODUCTS SET PRICE=25 WHERE ID=1;
DELETE FROM PRODUCTS WHERE ID=2;

SELECT * FROM PRODUCTS WHERE PRICE < (SELECT AVG(PRICE) FROM PRODUCTS);
SELECT * FROM PRODUCTS WHERE PRICE > 10;
SELECT * FROM PRODUCTS WHERE BRAND LENGTH > 5;